server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hexagonal
      authentication-database: admin
      username: root
      password: example



jana:
  client:
    address:
      url: http://localhost:8082/addresses